name: erp_app
description: ERP Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_remote_config: ^5.0.0
  firebase_crashlytics: ^4.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  crypto: ^3.0.3
  share_plus: ^9.0.0
  path_provider: ^2.1.2
  get: ^4.6.6
  vibration: ^1.7.5
  json_annotation: ^4.8.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
